### ISSUE TITLE
publish data

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/jipa#5]
@SimonGreenhill, you know WHEN your study will appear, right? should we publish the data along with this? And could you maybe add a .zenodo.json, so we have a correct quote for the JIPA study?

**Comment by xrotwang** [comment]
@SimonGreenhill any news on this?

**Comment by SimonGreenhill** [comment]
...proofs have just gone back. No idea about publication date yet sorry, but it shouldn't be far off :/

**Comment by xrotwang** [comment]
@SimonGreenhill so what would you suggest as citation? Anything better than
```bibtex
@article{BairdForth,
    title = {none},
    year = {2021}
}
```
will do :)

**Comment by SimonGreenhill** [comment]
Ok, this is all I know:

```bibtex
@article{BairdForth,
    title = {Blowing in the wind: Using North Wind and the Sun texts to sample phoneme inventories},
    authors = {Baird, Louise and Evans, Nicholas, and Greenhill, Simon J.},
    journal = {Journal of the International Phonetic Association},
    year = {2021}
}
```

**Comment by xrotwang** [comment]
That's good enough. I may add a
```
howpublished = {forthcoming},
```

Thanks!

**Comment by LinguList** [comment]
@SimonGreenhill, don't you have a DOI already? They often pass these with their proofs.

**Comment by tresoldi** [comment]
Paper is here: https://www.cambridge.org/core/journals/journal-of-the-international-phonetic-association/article/blowing-in-the-wind-using-north-wind-and-the-sun-texts-to-sample-phoneme-inventories/974F10F1A467914471E84E17496872E2

DOI: https://doi.org/10.1017/S002510032000033X

**Comment by LinguList** [comment]
```
@Article{Baird2021,
  author  = {Baird, Louise and Evans, Nicholas and Greenhill, Simon J.},
  title   = {Blowing in the wind: Using ‘North Wind and the Sun’ texts to sample phoneme inventories},
  doi     = {10.1017/S002510032000033X},
  number  = {0},
  pages   = {1-42},
  volume  = {0},
  journal = {Journal of the International Phonetic Association},
  year    = {2021},
}
```

**Comment by LinguList** [comment]
Volume and Number are set to 0, as this is out of an issue by now.

**Comment by SimonGreenhill** [comment]
Updated metadata.json in https://github.com/cldf-datasets/jipa/commit/69c67af2ef962ba19a77c4d69e549a72d2575320

**Comment by LinguList** [comment]
I think the data can be published with Zenodo now, right? We recompile, make a version, and release this. And on Zenodo, we can track back to the DOI.

**Comment by SimonGreenhill** [comment]
yes, just doing a few more updates.

**Comment by SimonGreenhill** [comment]
all done.

**Comment by xrotwang** [comment]
There's no release as far as I can tell.

**Comment by SimonGreenhill** [comment]
Ahh, ok just released v1.0: https://github.com/SimonGreenhill/jipa/releases

**Comment by xrotwang** [comment]
Maybe the plan was to use the raw data from SimonGreenhill/jipa via a git submodule. This isn't the case, though. As far as I can tell, only Amarasi.txt had updates which we don't have here. I'll sync this manually and then release the dataset here in cldf-datasets/jipa.

**Comment by xrotwang** [comment]
Done: https://github.com/cldf-datasets/jipa/releases/tag/v1.0
